### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by dangreaves** [jch254/docker-node-serverless#2]
In the last few days (or hours), it looks like the Docker image has been overwritten with a new version.

Since this update, we are getting the following error when running builds in Gitlab CI.

```sh
sls decrypt --stage dev --password 'XXX'

RangeError: Maximum call stack size exceeded
      at Function.[Symbol.hasInstance] (<anonymous>)
      at ReadStream (/builds/xxx/clients/xxx/xxx-integration/connector/node_modules/graceful-fs/graceful-fs.js:177:14)
      at ReadStream (/builds/xxx/clients/xxx/xxx-integration/connector/node_modules/graceful-fs/graceful-fs.js:178:28)
      // this line repeated hundreds of times
      at new ReadStream (/builds/xxx/clients/xxx/xxx-integration/connector/node_modules/graceful-fs/graceful-fs.js:178:28)
      at Object.createReadStream (/usr/local/share/.config/yarn/global/node_modules/graceful-fs/graceful-fs.js:302:12)
      at BbPromise (/builds/xxx/clients/xxx/xxx-integration/connector/node_modules/serverless-secrets-plugin/index.js:88:10)
      at ServerlessSecretsPlugin.decrypt (/builds/xxx/clients/xxx/xxx-integration/connector/node_modules/serverless-secrets-plugin/index.js:80:12)
      at BbPromise.reduce (/usr/local/share/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:504:55)
      at runCallback (timers.js:705:18)
      at tryOnImmediate (timers.js:676:5)
      at processImmediate (timers.js:658:5)
      at process.topLevelDomainCallback (domain.js:126:23)
```

It looks like it's caused by the Serverless update in 0aef47952328857cdfb79a0208406177f15f6387. Are you able to create a separate Docker version for 5315b46d32377fe9b42f91d607431b1123b5a770?

Many thanks, we really appreciate your work.

**Comment by jch254** [comment]
Hey Dan, sure no problem, I've created a new docker tag 1.51 so `jch254/docker-node-serverless:1.51` should work. I see there is a GitHub issue discussing what you're facing so hopefully it's fixed in other packages soon! https://github.com/serverless/serverless/issues/6667

**Comment by dangreaves** [comment]
Thanks so much @jch254 - you saved the day! 🎉

**Comment by jch254** [comment]
Hey @dangreaves I believe Serverless v1.51.2 should fix your issue as it contains https://github.com/serverless/serverless/pull/6717. I've just pushed up a commit updating so should be available under latest soon 👍

**Comment by jch254** [comment]
Hey @dangreaves do you still require `jch254/docker-node-serverless:1.51` or am I able to clean up? Cheers mate

**Comment by dangreaves** [comment]
Hey @jch254 - we may have some older projects where their build pipeline is still pinned to that version. I can have a look through and update them.

However, is there a need to remove the docker image? Ideally when a version is cut, it should stay forever, like npm and other package managers.

This means any dependents won’t be unexpectedly broken, where that version works fine for them, despite being old.

Unless I’m missing something?

**Comment by jch254** [comment]
Hey @dangreaves no worries, I was just wondering if the image was still being using, no need to  update. I was going through my DockerHub account and cleaning up automated builds that were not longer being used - e.g. removed the `8.10.0` images and tags as Lambda no longer supports Node.js 8.10. Cheers mate glad the project is helpful to others 👍
